/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as agent_conversation from "../agent/conversation.js";
import type * as agent_embeddingsCache from "../agent/embeddingsCache.js";
import type * as agent_memory from "../agent/memory.js";
import type * as aiTown_agent from "../aiTown/agent.js";
import type * as aiTown_agentDescription from "../aiTown/agentDescription.js";
import type * as aiTown_agentInputs from "../aiTown/agentInputs.js";
import type * as aiTown_agentOperations from "../aiTown/agentOperations.js";
import type * as aiTown_conversation from "../aiTown/conversation.js";
import type * as aiTown_conversationMembership from "../aiTown/conversationMembership.js";
import type * as aiTown_game from "../aiTown/game.js";
import type * as aiTown_ids from "../aiTown/ids.js";
import type * as aiTown_inputHandler from "../aiTown/inputHandler.js";
import type * as aiTown_inputs from "../aiTown/inputs.js";
import type * as aiTown_insertInput from "../aiTown/insertInput.js";
import type * as aiTown_location from "../aiTown/location.js";
import type * as aiTown_main from "../aiTown/main.js";
import type * as aiTown_movement from "../aiTown/movement.js";
import type * as aiTown_player from "../aiTown/player.js";
import type * as aiTown_playerDescription from "../aiTown/playerDescription.js";
import type * as aiTown_world from "../aiTown/world.js";
import type * as aiTown_worldMap from "../aiTown/worldMap.js";
import type * as constants from "../constants.js";
import type * as crons from "../crons.js";
import type * as engine_abstractGame from "../engine/abstractGame.js";
import type * as engine_historicalObject from "../engine/historicalObject.js";
import type * as init from "../init.js";
import type * as messages from "../messages.js";
import type * as music from "../music.js";
import type * as ours_actions_analyzeMoodImpact from "../ours/actions/analyzeMoodImpact.js";
import type * as ours_actions_chatWithTwin from "../ours/actions/chatWithTwin.js";
import type * as ours_actions_dedupActiveTwins from "../ours/actions/dedupActiveTwins.js";
import type * as ours_actions_dedupWorldPlayers from "../ours/actions/dedupWorldPlayers.js";
import type * as ours_actions_forceEndAllConversations from "../ours/actions/forceEndAllConversations.js";
import type * as ours_actions_interactionTakeTurn from "../ours/actions/interactionTakeTurn.js";
import type * as ours_actions_llmRouter from "../ours/actions/llmRouter.js";
import type * as ours_actions_piiScan from "../ours/actions/piiScan.js";
import type * as ours_actions_probeMinimaxEmbedding from "../ours/actions/probeMinimaxEmbedding.js";
import type * as ours_actions_promptInjectionScan from "../ours/actions/promptInjectionScan.js";
import type * as ours_actions_refreshAllInWorld from "../ours/actions/refreshAllInWorld.js";
import type * as ours_actions_removeNpcsAndPromoteStudents from "../ours/actions/removeNpcsAndPromoteStudents.js";
import type * as ours_actions_removeSeededNpcs from "../ours/actions/removeSeededNpcs.js";
import type * as ours_actions_runTwinScans from "../ours/actions/runTwinScans.js";
import type * as ours_actions_seedNpcCards from "../ours/actions/seedNpcCards.js";
import type * as ours_actions_seedTownPlayers from "../ours/actions/seedTownPlayers.js";
import type * as ours_actions_seedTwinsForGame from "../ours/actions/seedTwinsForGame.js";
import type * as ours_actions_softResetWorld from "../ours/actions/softResetWorld.js";
import type * as ours_actions_unblockClassifierErroredTwins from "../ours/actions/unblockClassifierErroredTwins.js";
import type * as ours_actions_uploadTwin from "../ours/actions/uploadTwin.js";
import type * as ours_actions_verifyChatAccess from "../ours/actions/verifyChatAccess.js";
import type * as ours_crons_engineWatchdog from "../ours/crons/engineWatchdog.js";
import type * as ours_crons_engineWatchdogMutation from "../ours/crons/engineWatchdogMutation.js";
import type * as ours_crons_interactionTick from "../ours/crons/interactionTick.js";
import type * as ours_crons_moodDecay from "../ours/crons/moodDecay.js";
import type * as ours_crons_sessionWindow from "../ours/crons/sessionWindow.js";
import type * as ours_data_npcCards from "../ours/data/npcCards.js";
import type * as ours_interactions_gameRegistry from "../ours/interactions/gameRegistry.js";
import type * as ours_interactions_types from "../ours/interactions/types.js";
import type * as ours_interactions_werewolf_index from "../ours/interactions/werewolf/index.js";
import type * as ours_interactions_werewolf_prompts from "../ours/interactions/werewolf/prompts.js";
import type * as ours_interactions_werewolf_rules from "../ours/interactions/werewolf/rules.js";
import type * as ours_interactions_werewolf_state from "../ours/interactions/werewolf/state.js";
import type * as ours_lib_authCodeStore from "../ours/lib/authCodeStore.js";
import type * as ours_lib_cardValidator from "../ours/lib/cardValidator.js";
import type * as ours_lib_chatAuth from "../ours/lib/chatAuth.js";
import type * as ours_lib_codes from "../ours/lib/codes.js";
import type * as ours_lib_deepseekClient from "../ours/lib/deepseekClient.js";
import type * as ours_lib_dungeonBridge from "../ours/lib/dungeonBridge.js";
import type * as ours_lib_finalizeScanCore from "../ours/lib/finalizeScanCore.js";
import type * as ours_lib_idempotency from "../ours/lib/idempotency.js";
import type * as ours_lib_instructorAuth from "../ours/lib/instructorAuth.js";
import type * as ours_lib_llmRouterCore from "../ours/lib/llmRouterCore.js";
import type * as ours_lib_minimaxEmbedding from "../ours/lib/minimaxEmbedding.js";
import type * as ours_lib_parseCard from "../ours/lib/parseCard.js";
import type * as ours_lib_piiPatterns from "../ours/lib/piiPatterns.js";
import type * as ours_lib_piiScanCore from "../ours/lib/piiScanCore.js";
import type * as ours_lib_promptInjectionScanCore from "../ours/lib/promptInjectionScanCore.js";
import type * as ours_lib_rateLimit from "../ours/lib/rateLimit.js";
import type * as ours_lib_session from "../ours/lib/session.js";
import type * as ours_lib_sessionWindowCore from "../ours/lib/sessionWindowCore.js";
import type * as ours_lib_spendTracking from "../ours/lib/spendTracking.js";
import type * as ours_lib_togetherClient from "../ours/lib/togetherClient.js";
import type * as ours_lib_townChatModel from "../ours/lib/townChatModel.js";
import type * as ours_lib_uploadFlowCore from "../ours/lib/uploadFlowCore.js";
import type * as ours_lib_uploadPayload from "../ours/lib/uploadPayload.js";
import type * as ours_lib_uploadResultsStore from "../ours/lib/uploadResultsStore.js";
import type * as ours_lib_worldState from "../ours/lib/worldState.js";
import type * as ours_mutations_addAgentDailySpend from "../ours/mutations/addAgentDailySpend.js";
import type * as ours_mutations_appendInteractionTurn from "../ours/mutations/appendInteractionTurn.js";
import type * as ours_mutations_applyScheduledStatus from "../ours/mutations/applyScheduledStatus.js";
import type * as ours_mutations_backfillCardIntros from "../ours/mutations/backfillCardIntros.js";
import type * as ours_mutations_cancelInteraction from "../ours/mutations/cancelInteraction.js";
import type * as ours_mutations_checkAndIncrementAttempts from "../ours/mutations/checkAndIncrementAttempts.js";
import type * as ours_mutations_clearTownEvent from "../ours/mutations/clearTownEvent.js";
import type * as ours_mutations_clearUploadResult from "../ours/mutations/clearUploadResult.js";
import type * as ours_mutations_createPendingTwin from "../ours/mutations/createPendingTwin.js";
import type * as ours_mutations_createSession from "../ours/mutations/createSession.js";
import type * as ours_mutations_deleteTwinByPseudonym from "../ours/mutations/deleteTwinByPseudonym.js";
import type * as ours_mutations_devForceFreezeWorld from "../ours/mutations/devForceFreezeWorld.js";
import type * as ours_mutations_devForceResumeWorld from "../ours/mutations/devForceResumeWorld.js";
import type * as ours_mutations_finalizeScan from "../ours/mutations/finalizeScan.js";
import type * as ours_mutations_findOrCreateTwinForAgent from "../ours/mutations/findOrCreateTwinForAgent.js";
import type * as ours_mutations_freezeWorld from "../ours/mutations/freezeWorld.js";
import type * as ours_mutations_insertGeneratedTwins from "../ours/mutations/insertGeneratedTwins.js";
import type * as ours_mutations_instructorAuthenticate from "../ours/mutations/instructorAuthenticate.js";
import type * as ours_mutations_instructorRegister from "../ours/mutations/instructorRegister.js";
import type * as ours_mutations_issueCode from "../ours/mutations/issueCode.js";
import type * as ours_mutations_kickEngine from "../ours/mutations/kickEngine.js";
import type * as ours_mutations_leaveTwinsFromTown from "../ours/mutations/leaveTwinsFromTown.js";
import type * as ours_mutations_markSeededNpcsSynthetic from "../ours/mutations/markSeededNpcsSynthetic.js";
import type * as ours_mutations_promoteTwinToAgent from "../ours/mutations/promoteTwinToAgent.js";
import type * as ours_mutations_queueCreateAgentInline from "../ours/mutations/queueCreateAgentInline.js";
import type * as ours_mutations_recordCacheStats from "../ours/mutations/recordCacheStats.js";
import type * as ours_mutations_recordLlmCall from "../ours/mutations/recordLlmCall.js";
import type * as ours_mutations_renameTwin from "../ours/mutations/renameTwin.js";
import type * as ours_mutations_resumeWorld from "../ours/mutations/resumeWorld.js";
import type * as ours_mutations_setAgentMood from "../ours/mutations/setAgentMood.js";
import type * as ours_mutations_setInteractionInflight from "../ours/mutations/setInteractionInflight.js";
import type * as ours_mutations_setTownEvent from "../ours/mutations/setTownEvent.js";
import type * as ours_mutations_startDungeonGame from "../ours/mutations/startDungeonGame.js";
import type * as ours_mutations_startInteraction from "../ours/mutations/startInteraction.js";
import type * as ours_mutations_swapMap from "../ours/mutations/swapMap.js";
import type * as ours_mutations_wipeEmbeddings from "../ours/mutations/wipeEmbeddings.js";
import type * as ours_queries_auditCardIntros from "../ours/queries/auditCardIntros.js";
import type * as ours_queries_debugPlayerLookup from "../ours/queries/debugPlayerLookup.js";
import type * as ours_queries_defaultWorldStatus from "../ours/queries/defaultWorldStatus.js";
import type * as ours_queries_dumpAgentIdentity from "../ours/queries/dumpAgentIdentity.js";
import type * as ours_queries_dumpFullCard from "../ours/queries/dumpFullCard.js";
import type * as ours_queries_dumpTwinHashes from "../ours/queries/dumpTwinHashes.js";
import type * as ours_queries_engineState from "../ours/queries/engineState.js";
import type * as ours_queries_getAgentDailySpend from "../ours/queries/getAgentDailySpend.js";
import type * as ours_queries_getAgentMood from "../ours/queries/getAgentMood.js";
import type * as ours_queries_getCachedLlmCall from "../ours/queries/getCachedLlmCall.js";
import type * as ours_queries_getCardForScan from "../ours/queries/getCardForScan.js";
import type * as ours_queries_getInteraction from "../ours/queries/getInteraction.js";
import type * as ours_queries_getInteractionContext from "../ours/queries/getInteractionContext.js";
import type * as ours_queries_getSession from "../ours/queries/getSession.js";
import type * as ours_queries_getTownEvent from "../ours/queries/getTownEvent.js";
import type * as ours_queries_inspectCard from "../ours/queries/inspectCard.js";
import type * as ours_queries_instructorActiveInteractions from "../ours/queries/instructorActiveInteractions.js";
import type * as ours_queries_instructorSession from "../ours/queries/instructorSession.js";
import type * as ours_queries_instructorTownAgents from "../ours/queries/instructorTownAgents.js";
import type * as ours_queries_instructorTwinList from "../ours/queries/instructorTwinList.js";
import type * as ours_queries_listActiveInteractions from "../ours/queries/listActiveInteractions.js";
import type * as ours_queries_listAgentMoods from "../ours/queries/listAgentMoods.js";
import type * as ours_queries_listAllPlayers from "../ours/queries/listAllPlayers.js";
import type * as ours_queries_listInteractionTurns from "../ours/queries/listInteractionTurns.js";
import type * as ours_queries_listTwinsByState from "../ours/queries/listTwinsByState.js";
import type * as ours_queries_llmCacheReport from "../ours/queries/llmCacheReport.js";
import type * as ours_queries_playerConversations from "../ours/queries/playerConversations.js";
import type * as ours_queries_playerReflections from "../ours/queries/playerReflections.js";
import type * as ours_queries_rejectedTwinDetail from "../ours/queries/rejectedTwinDetail.js";
import type * as ours_queries_spectatorInteraction from "../ours/queries/spectatorInteraction.js";
import type * as ours_queries_twinsForChatByPseudonym from "../ours/queries/twinsForChatByPseudonym.js";
import type * as ours_queries_uploadResultByToken from "../ours/queries/uploadResultByToken.js";
import type * as ours_queries_verifyCode from "../ours/queries/verifyCode.js";
import type * as ours_queries_worldStatus from "../ours/queries/worldStatus.js";
import type * as ours_tables_agentDailySpend from "../ours/tables/agentDailySpend.js";
import type * as ours_tables_agentMoods from "../ours/tables/agentMoods.js";
import type * as ours_tables_auditLog from "../ours/tables/auditLog.js";
import type * as ours_tables_authCodes from "../ours/tables/authCodes.js";
import type * as ours_tables_cards from "../ours/tables/cards.js";
import type * as ours_tables_consents from "../ours/tables/consents.js";
import type * as ours_tables_crossBorderTransfers from "../ours/tables/crossBorderTransfers.js";
import type * as ours_tables_digests from "../ours/tables/digests.js";
import type * as ours_tables_dungeonReturnState from "../ours/tables/dungeonReturnState.js";
import type * as ours_tables_engineWatchdog from "../ours/tables/engineWatchdog.js";
import type * as ours_tables_index from "../ours/tables/index.js";
import type * as ours_tables_instructorAuthenticators from "../ours/tables/instructorAuthenticators.js";
import type * as ours_tables_instructorChallenges from "../ours/tables/instructorChallenges.js";
import type * as ours_tables_instructorSessions from "../ours/tables/instructorSessions.js";
import type * as ours_tables_instructors from "../ours/tables/instructors.js";
import type * as ours_tables_interactionMemories from "../ours/tables/interactionMemories.js";
import type * as ours_tables_interactionTurns from "../ours/tables/interactionTurns.js";
import type * as ours_tables_interactions from "../ours/tables/interactions.js";
import type * as ours_tables_llmCacheStats from "../ours/tables/llmCacheStats.js";
import type * as ours_tables_llmCallIdempotency from "../ours/tables/llmCallIdempotency.js";
import type * as ours_tables_noticeboard from "../ours/tables/noticeboard.js";
import type * as ours_tables_objects from "../ours/tables/objects.js";
import type * as ours_tables_rateLimits from "../ours/tables/rateLimits.js";
import type * as ours_tables_reflections from "../ours/tables/reflections.js";
import type * as ours_tables_retractions from "../ours/tables/retractions.js";
import type * as ours_tables_studentSessions from "../ours/tables/studentSessions.js";
import type * as ours_tables_townEventState from "../ours/tables/townEventState.js";
import type * as ours_tables_twins from "../ours/tables/twins.js";
import type * as ours_tables_uploadResults from "../ours/tables/uploadResults.js";
import type * as ours_tables_worldState from "../ours/tables/worldState.js";
import type * as ours_townHooks from "../ours/townHooks.js";
import type * as testing from "../testing.js";
import type * as util_FastIntegerCompression from "../util/FastIntegerCompression.js";
import type * as util_assertNever from "../util/assertNever.js";
import type * as util_asyncMap from "../util/asyncMap.js";
import type * as util_compression from "../util/compression.js";
import type * as util_geometry from "../util/geometry.js";
import type * as util_isSimpleObject from "../util/isSimpleObject.js";
import type * as util_llm from "../util/llm.js";
import type * as util_minheap from "../util/minheap.js";
import type * as util_object from "../util/object.js";
import type * as util_sleep from "../util/sleep.js";
import type * as util_types from "../util/types.js";
import type * as util_xxhash from "../util/xxhash.js";
import type * as world from "../world.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "agent/conversation": typeof agent_conversation;
  "agent/embeddingsCache": typeof agent_embeddingsCache;
  "agent/memory": typeof agent_memory;
  "aiTown/agent": typeof aiTown_agent;
  "aiTown/agentDescription": typeof aiTown_agentDescription;
  "aiTown/agentInputs": typeof aiTown_agentInputs;
  "aiTown/agentOperations": typeof aiTown_agentOperations;
  "aiTown/conversation": typeof aiTown_conversation;
  "aiTown/conversationMembership": typeof aiTown_conversationMembership;
  "aiTown/game": typeof aiTown_game;
  "aiTown/ids": typeof aiTown_ids;
  "aiTown/inputHandler": typeof aiTown_inputHandler;
  "aiTown/inputs": typeof aiTown_inputs;
  "aiTown/insertInput": typeof aiTown_insertInput;
  "aiTown/location": typeof aiTown_location;
  "aiTown/main": typeof aiTown_main;
  "aiTown/movement": typeof aiTown_movement;
  "aiTown/player": typeof aiTown_player;
  "aiTown/playerDescription": typeof aiTown_playerDescription;
  "aiTown/world": typeof aiTown_world;
  "aiTown/worldMap": typeof aiTown_worldMap;
  constants: typeof constants;
  crons: typeof crons;
  "engine/abstractGame": typeof engine_abstractGame;
  "engine/historicalObject": typeof engine_historicalObject;
  init: typeof init;
  messages: typeof messages;
  music: typeof music;
  "ours/actions/analyzeMoodImpact": typeof ours_actions_analyzeMoodImpact;
  "ours/actions/chatWithTwin": typeof ours_actions_chatWithTwin;
  "ours/actions/dedupActiveTwins": typeof ours_actions_dedupActiveTwins;
  "ours/actions/dedupWorldPlayers": typeof ours_actions_dedupWorldPlayers;
  "ours/actions/forceEndAllConversations": typeof ours_actions_forceEndAllConversations;
  "ours/actions/interactionTakeTurn": typeof ours_actions_interactionTakeTurn;
  "ours/actions/llmRouter": typeof ours_actions_llmRouter;
  "ours/actions/piiScan": typeof ours_actions_piiScan;
  "ours/actions/probeMinimaxEmbedding": typeof ours_actions_probeMinimaxEmbedding;
  "ours/actions/promptInjectionScan": typeof ours_actions_promptInjectionScan;
  "ours/actions/refreshAllInWorld": typeof ours_actions_refreshAllInWorld;
  "ours/actions/removeNpcsAndPromoteStudents": typeof ours_actions_removeNpcsAndPromoteStudents;
  "ours/actions/removeSeededNpcs": typeof ours_actions_removeSeededNpcs;
  "ours/actions/runTwinScans": typeof ours_actions_runTwinScans;
  "ours/actions/seedNpcCards": typeof ours_actions_seedNpcCards;
  "ours/actions/seedTownPlayers": typeof ours_actions_seedTownPlayers;
  "ours/actions/seedTwinsForGame": typeof ours_actions_seedTwinsForGame;
  "ours/actions/softResetWorld": typeof ours_actions_softResetWorld;
  "ours/actions/unblockClassifierErroredTwins": typeof ours_actions_unblockClassifierErroredTwins;
  "ours/actions/uploadTwin": typeof ours_actions_uploadTwin;
  "ours/actions/verifyChatAccess": typeof ours_actions_verifyChatAccess;
  "ours/crons/engineWatchdog": typeof ours_crons_engineWatchdog;
  "ours/crons/engineWatchdogMutation": typeof ours_crons_engineWatchdogMutation;
  "ours/crons/interactionTick": typeof ours_crons_interactionTick;
  "ours/crons/moodDecay": typeof ours_crons_moodDecay;
  "ours/crons/sessionWindow": typeof ours_crons_sessionWindow;
  "ours/data/npcCards": typeof ours_data_npcCards;
  "ours/interactions/gameRegistry": typeof ours_interactions_gameRegistry;
  "ours/interactions/types": typeof ours_interactions_types;
  "ours/interactions/werewolf/index": typeof ours_interactions_werewolf_index;
  "ours/interactions/werewolf/prompts": typeof ours_interactions_werewolf_prompts;
  "ours/interactions/werewolf/rules": typeof ours_interactions_werewolf_rules;
  "ours/interactions/werewolf/state": typeof ours_interactions_werewolf_state;
  "ours/lib/authCodeStore": typeof ours_lib_authCodeStore;
  "ours/lib/cardValidator": typeof ours_lib_cardValidator;
  "ours/lib/chatAuth": typeof ours_lib_chatAuth;
  "ours/lib/codes": typeof ours_lib_codes;
  "ours/lib/deepseekClient": typeof ours_lib_deepseekClient;
  "ours/lib/dungeonBridge": typeof ours_lib_dungeonBridge;
  "ours/lib/finalizeScanCore": typeof ours_lib_finalizeScanCore;
  "ours/lib/idempotency": typeof ours_lib_idempotency;
  "ours/lib/instructorAuth": typeof ours_lib_instructorAuth;
  "ours/lib/llmRouterCore": typeof ours_lib_llmRouterCore;
  "ours/lib/minimaxEmbedding": typeof ours_lib_minimaxEmbedding;
  "ours/lib/parseCard": typeof ours_lib_parseCard;
  "ours/lib/piiPatterns": typeof ours_lib_piiPatterns;
  "ours/lib/piiScanCore": typeof ours_lib_piiScanCore;
  "ours/lib/promptInjectionScanCore": typeof ours_lib_promptInjectionScanCore;
  "ours/lib/rateLimit": typeof ours_lib_rateLimit;
  "ours/lib/session": typeof ours_lib_session;
  "ours/lib/sessionWindowCore": typeof ours_lib_sessionWindowCore;
  "ours/lib/spendTracking": typeof ours_lib_spendTracking;
  "ours/lib/togetherClient": typeof ours_lib_togetherClient;
  "ours/lib/townChatModel": typeof ours_lib_townChatModel;
  "ours/lib/uploadFlowCore": typeof ours_lib_uploadFlowCore;
  "ours/lib/uploadPayload": typeof ours_lib_uploadPayload;
  "ours/lib/uploadResultsStore": typeof ours_lib_uploadResultsStore;
  "ours/lib/worldState": typeof ours_lib_worldState;
  "ours/mutations/addAgentDailySpend": typeof ours_mutations_addAgentDailySpend;
  "ours/mutations/appendInteractionTurn": typeof ours_mutations_appendInteractionTurn;
  "ours/mutations/applyScheduledStatus": typeof ours_mutations_applyScheduledStatus;
  "ours/mutations/backfillCardIntros": typeof ours_mutations_backfillCardIntros;
  "ours/mutations/cancelInteraction": typeof ours_mutations_cancelInteraction;
  "ours/mutations/checkAndIncrementAttempts": typeof ours_mutations_checkAndIncrementAttempts;
  "ours/mutations/clearTownEvent": typeof ours_mutations_clearTownEvent;
  "ours/mutations/clearUploadResult": typeof ours_mutations_clearUploadResult;
  "ours/mutations/createPendingTwin": typeof ours_mutations_createPendingTwin;
  "ours/mutations/createSession": typeof ours_mutations_createSession;
  "ours/mutations/deleteTwinByPseudonym": typeof ours_mutations_deleteTwinByPseudonym;
  "ours/mutations/devForceFreezeWorld": typeof ours_mutations_devForceFreezeWorld;
  "ours/mutations/devForceResumeWorld": typeof ours_mutations_devForceResumeWorld;
  "ours/mutations/finalizeScan": typeof ours_mutations_finalizeScan;
  "ours/mutations/findOrCreateTwinForAgent": typeof ours_mutations_findOrCreateTwinForAgent;
  "ours/mutations/freezeWorld": typeof ours_mutations_freezeWorld;
  "ours/mutations/insertGeneratedTwins": typeof ours_mutations_insertGeneratedTwins;
  "ours/mutations/instructorAuthenticate": typeof ours_mutations_instructorAuthenticate;
  "ours/mutations/instructorRegister": typeof ours_mutations_instructorRegister;
  "ours/mutations/issueCode": typeof ours_mutations_issueCode;
  "ours/mutations/kickEngine": typeof ours_mutations_kickEngine;
  "ours/mutations/leaveTwinsFromTown": typeof ours_mutations_leaveTwinsFromTown;
  "ours/mutations/markSeededNpcsSynthetic": typeof ours_mutations_markSeededNpcsSynthetic;
  "ours/mutations/promoteTwinToAgent": typeof ours_mutations_promoteTwinToAgent;
  "ours/mutations/queueCreateAgentInline": typeof ours_mutations_queueCreateAgentInline;
  "ours/mutations/recordCacheStats": typeof ours_mutations_recordCacheStats;
  "ours/mutations/recordLlmCall": typeof ours_mutations_recordLlmCall;
  "ours/mutations/renameTwin": typeof ours_mutations_renameTwin;
  "ours/mutations/resumeWorld": typeof ours_mutations_resumeWorld;
  "ours/mutations/setAgentMood": typeof ours_mutations_setAgentMood;
  "ours/mutations/setInteractionInflight": typeof ours_mutations_setInteractionInflight;
  "ours/mutations/setTownEvent": typeof ours_mutations_setTownEvent;
  "ours/mutations/startDungeonGame": typeof ours_mutations_startDungeonGame;
  "ours/mutations/startInteraction": typeof ours_mutations_startInteraction;
  "ours/mutations/swapMap": typeof ours_mutations_swapMap;
  "ours/mutations/wipeEmbeddings": typeof ours_mutations_wipeEmbeddings;
  "ours/queries/auditCardIntros": typeof ours_queries_auditCardIntros;
  "ours/queries/debugPlayerLookup": typeof ours_queries_debugPlayerLookup;
  "ours/queries/defaultWorldStatus": typeof ours_queries_defaultWorldStatus;
  "ours/queries/dumpAgentIdentity": typeof ours_queries_dumpAgentIdentity;
  "ours/queries/dumpFullCard": typeof ours_queries_dumpFullCard;
  "ours/queries/dumpTwinHashes": typeof ours_queries_dumpTwinHashes;
  "ours/queries/engineState": typeof ours_queries_engineState;
  "ours/queries/getAgentDailySpend": typeof ours_queries_getAgentDailySpend;
  "ours/queries/getAgentMood": typeof ours_queries_getAgentMood;
  "ours/queries/getCachedLlmCall": typeof ours_queries_getCachedLlmCall;
  "ours/queries/getCardForScan": typeof ours_queries_getCardForScan;
  "ours/queries/getInteraction": typeof ours_queries_getInteraction;
  "ours/queries/getInteractionContext": typeof ours_queries_getInteractionContext;
  "ours/queries/getSession": typeof ours_queries_getSession;
  "ours/queries/getTownEvent": typeof ours_queries_getTownEvent;
  "ours/queries/inspectCard": typeof ours_queries_inspectCard;
  "ours/queries/instructorActiveInteractions": typeof ours_queries_instructorActiveInteractions;
  "ours/queries/instructorSession": typeof ours_queries_instructorSession;
  "ours/queries/instructorTownAgents": typeof ours_queries_instructorTownAgents;
  "ours/queries/instructorTwinList": typeof ours_queries_instructorTwinList;
  "ours/queries/listActiveInteractions": typeof ours_queries_listActiveInteractions;
  "ours/queries/listAgentMoods": typeof ours_queries_listAgentMoods;
  "ours/queries/listAllPlayers": typeof ours_queries_listAllPlayers;
  "ours/queries/listInteractionTurns": typeof ours_queries_listInteractionTurns;
  "ours/queries/listTwinsByState": typeof ours_queries_listTwinsByState;
  "ours/queries/llmCacheReport": typeof ours_queries_llmCacheReport;
  "ours/queries/playerConversations": typeof ours_queries_playerConversations;
  "ours/queries/playerReflections": typeof ours_queries_playerReflections;
  "ours/queries/rejectedTwinDetail": typeof ours_queries_rejectedTwinDetail;
  "ours/queries/spectatorInteraction": typeof ours_queries_spectatorInteraction;
  "ours/queries/twinsForChatByPseudonym": typeof ours_queries_twinsForChatByPseudonym;
  "ours/queries/uploadResultByToken": typeof ours_queries_uploadResultByToken;
  "ours/queries/verifyCode": typeof ours_queries_verifyCode;
  "ours/queries/worldStatus": typeof ours_queries_worldStatus;
  "ours/tables/agentDailySpend": typeof ours_tables_agentDailySpend;
  "ours/tables/agentMoods": typeof ours_tables_agentMoods;
  "ours/tables/auditLog": typeof ours_tables_auditLog;
  "ours/tables/authCodes": typeof ours_tables_authCodes;
  "ours/tables/cards": typeof ours_tables_cards;
  "ours/tables/consents": typeof ours_tables_consents;
  "ours/tables/crossBorderTransfers": typeof ours_tables_crossBorderTransfers;
  "ours/tables/digests": typeof ours_tables_digests;
  "ours/tables/dungeonReturnState": typeof ours_tables_dungeonReturnState;
  "ours/tables/engineWatchdog": typeof ours_tables_engineWatchdog;
  "ours/tables/index": typeof ours_tables_index;
  "ours/tables/instructorAuthenticators": typeof ours_tables_instructorAuthenticators;
  "ours/tables/instructorChallenges": typeof ours_tables_instructorChallenges;
  "ours/tables/instructorSessions": typeof ours_tables_instructorSessions;
  "ours/tables/instructors": typeof ours_tables_instructors;
  "ours/tables/interactionMemories": typeof ours_tables_interactionMemories;
  "ours/tables/interactionTurns": typeof ours_tables_interactionTurns;
  "ours/tables/interactions": typeof ours_tables_interactions;
  "ours/tables/llmCacheStats": typeof ours_tables_llmCacheStats;
  "ours/tables/llmCallIdempotency": typeof ours_tables_llmCallIdempotency;
  "ours/tables/noticeboard": typeof ours_tables_noticeboard;
  "ours/tables/objects": typeof ours_tables_objects;
  "ours/tables/rateLimits": typeof ours_tables_rateLimits;
  "ours/tables/reflections": typeof ours_tables_reflections;
  "ours/tables/retractions": typeof ours_tables_retractions;
  "ours/tables/studentSessions": typeof ours_tables_studentSessions;
  "ours/tables/townEventState": typeof ours_tables_townEventState;
  "ours/tables/twins": typeof ours_tables_twins;
  "ours/tables/uploadResults": typeof ours_tables_uploadResults;
  "ours/tables/worldState": typeof ours_tables_worldState;
  "ours/townHooks": typeof ours_townHooks;
  testing: typeof testing;
  "util/FastIntegerCompression": typeof util_FastIntegerCompression;
  "util/assertNever": typeof util_assertNever;
  "util/asyncMap": typeof util_asyncMap;
  "util/compression": typeof util_compression;
  "util/geometry": typeof util_geometry;
  "util/isSimpleObject": typeof util_isSimpleObject;
  "util/llm": typeof util_llm;
  "util/minheap": typeof util_minheap;
  "util/object": typeof util_object;
  "util/sleep": typeof util_sleep;
  "util/types": typeof util_types;
  "util/xxhash": typeof util_xxhash;
  world: typeof world;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
